// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mniak/duplicomp (interfaces: ShadowLogger)

// Package tests is a generated GoMock package.
package tests

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockShadowLogger is a mock of ShadowLogger interface.
type MockShadowLogger struct {
	ctrl     *gomock.Controller
	recorder *MockShadowLoggerMockRecorder
}

// MockShadowLoggerMockRecorder is the mock recorder for MockShadowLogger.
type MockShadowLoggerMockRecorder struct {
	mock *MockShadowLogger
}

// NewMockShadowLogger creates a new mock instance.
func NewMockShadowLogger(ctrl *gomock.Controller) *MockShadowLogger {
	mock := &MockShadowLogger{ctrl: ctrl}
	mock.recorder = &MockShadowLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShadowLogger) EXPECT() *MockShadowLoggerMockRecorder {
	return m.recorder
}

// LogCompareReceive mocks base method.
func (m *MockShadowLogger) LogCompareReceive(arg0, arg1 protoreflect.ProtoMessage, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCompareReceive", arg0, arg1, arg2)
}

// LogCompareReceive indicates an expected call of LogCompareReceive.
func (mr *MockShadowLoggerMockRecorder) LogCompareReceive(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCompareReceive", reflect.TypeOf((*MockShadowLogger)(nil).LogCompareReceive), arg0, arg1, arg2)
}

// LogSendFailure mocks base method.
func (m *MockShadowLogger) LogSendFailure(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogSendFailure", arg0)
}

// LogSendFailure indicates an expected call of LogSendFailure.
func (mr *MockShadowLoggerMockRecorder) LogSendFailure(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSendFailure", reflect.TypeOf((*MockShadowLogger)(nil).LogSendFailure), arg0)
}
